{% set name = "sed3" %}
{% set version = "1.2.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "3476a5afb1bf7e02151b8c23f296643cb5223b080f7385c652eccb71b4f7e744" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - matplotlib
    - pyyaml
    - scipy
  run:
    - python
    - matplotlib
    - pyyaml
    - scipy
    - pyqt 4.11.*

test:
  imports:
    - sed3

about:
  home: https://github.com/mjirik/py3DSeedEditor
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: 3D viewer and editor of color seeds
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
