package:
  name: pysegbase
  version: "1.0.43"

source:
  fn: pysegbase-1.0.43.tar.gz
  url: https://pypi.python.org/packages/source/p/pysegbase/pysegbase-1.0.43.tar.gz
  md5: 6bfc621c1880960794ed58cae0d39b70
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysegbase = pysegbase:main
    #
    # Would create an entry point called pysegbase that calls pysegbase.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pyqt

  run:
    - python
    - numpy
    - scipy
    - pyqt

test:
  # Python imports
  imports:
    - pysegbase

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/pyseg_base
  license: BSD License
  summary: 'Graph Cut based 3D segmentation with editor'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
