package:
  name: checksumdir
  version: "1.1.4"

source:
  fn: checksumdir-1.1.4.tar.gz
  url: https://pypi.python.org/packages/84/8b/0e800a118ed64091245feddef0159d7979bb42915f65db5d2dafd6b12864/checksumdir-1.1.4.tar.gz
  md5: d8caf4403c765930bf5fff458ce364f7
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - checksumdir = checksumdir:main
    #
    # Would create an entry point called checksumdir that calls checksumdir.main()

    - checksumdir=checksumdir.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - checksumdir

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - checksumdir --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cakepietoast/checksumdir
  license: MIT License
  summary: 'Compute a single hash of the file contents of a directory.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
