{% set name = "wget" %}
{% set version = "3.2" %}
{% set file_ext = "zip" %}
{% set hash_type = "sha256" %}
{% set hash_value = "35e630eca2aa50ce998b9b1a127bb26b30dfee573702782aa982f875e3f16061" %}

package:
  name: 'py{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  host:
    - python
  run:
    - python

about:
  home: http://bitbucket.org/techtonik/python-wget/
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: ''
  summary: pure python download utility
  description: "Usage\n=====\n\n  python -m wget [options] <URL>\n\n  options:\n    -o --output FILE|DIR   output filename or directory\n\n\nAPI Usage\n=========\n\n  >>> import wget\n  >>> url = 'http://www.futurecrew.com/skaven/song_files/mp3/razorback.mp3'\n\
    \  >>> filename = wget.download(url)\n  100% [................................................] 3841532 / 3841532>\n  >> filename\n  'razorback.mp3'\n\nThe skew that you see above is a documented side\
    \ effect.\nAlternative progress bar:\n\n  >>> wget.download(url, bar=bar_thermometer)\n\n\nChangeLog\n=========\n3.2 (2015-10-22)\n * download(url) can again be unicode on Python 2.7\n   https://bitbucket.org/techtonik/python-wget/issues/8\n\
    \n3.1 (2015-10-18)\n * it saves unknown files under download.wget filename\n   https://bitbucket.org/techtonik/python-wget/issues/6\n * it prints unicode chars to Windows console\n * it downloads unicode\
    \ urls with Python 3\n\n3.0 (2015-10-17)\n * it can download and save unicode filenames\n   https://bitbucket.org/techtonik/python-wget/issues/7\n\n2.2 (2014-07-19)\n * it again can download without\
    \ -o option\n\n2.1 (2014-07-10)\n * it shows command line help\n * -o option allows to select output file/directory\n\n   * download(url, out, bar) contains out parameter\n\n2.0 (2013-04-26)\n * it\
    \ shows percentage\n * it has usage examples\n * it changes if being used as a library\n\n   * download shows progress bar by default\n   * bar_adaptive gets improved algorithm\n   * download(url, bar)\
    \ contains bar parameter\n     * bar(current, total)\n   * progress_callback is named callback_progress\n\n1.0 (2012-11-13)\n * it runs with Python 3\n\n0.9 (2012-11-13)\n * it renames file if it already\
    \ exists\n * it can be used as a library\n\n   * download(url) returns filename\n   * bar_adaptive() draws progress bar\n   * bar_thermometer() simplified bar\n\n0.8 (2011-05-03)\n * it detects filename\
    \ from HTTP headers\n\n0.7 (2011-03-01)\n * compatibility fix for Python 2.5\n * limit width of progress bar to 100 chars\n\n0.6 (2010-04-24)\n * it detects console width on POSIX\n\n0.5 (2010-04-23)\n\
    \ * it detects console width on Windows\n\n0.4 (2010-04-15)\n * it shows cute progress bar\n\n0.3 (2010-04-05)\n * it creates temp file in current dir\n\n0.2 (2010-02-16)\n * it tries to detect filename\
    \ from URL\n\n0.1 (2010-02-04)\n * it can download file\n\n\nRelease Checklist\n=================\n\n| [ ] update version in wget.py\n| [x] update description in setup.py\n| [ ] python setup.py check\
    \ -mrs\n| [ ] python setup.py sdist upload\n| [ ] tag hg version\n\n-- \nanatoly techtonik <techtonik@gmail.com>"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
